apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  #     nodePort: 31010
  # type: NodePort
  selector:
    app: mysql
