apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: hoangledinh65/rest-springboot
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: java
        volumeMounts:
          - name: volume1
            mountPath: /etc/file1
            readOnly: true
            # subPath: 
            #   file1
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: volume1
          configMap:
            name: java-cfg2
            
