apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: java
    env: test
spec:
  containers:
  - name: java
    image: hoangledinh65/rest-springboot
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: java
  imagePullSecrets:
  - name: regcred
