apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: java
    env: test
spec:
  containers:
  - name: java
    image: hoangledinh65/rest-springboot:latest
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: regcred
