apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hoangdl-cluster
  region: ap-southeast-1
nodeGroups:
  # - name: ng-1
  #   instanceType: m5.large
  #   desiredCapacity: 10
  #   volumeSize: 80
  #   ssh:
  #     allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      publicKeyPath: ~/.ssh/ec2.pub
