apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    env: prod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: 500Mi"
    ports:
      - containerPort: 80
    command: ["/bin/bash", "-c"]
    args:
      - tail -f /dev/null
