apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoangdl-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0ce510ddd981a76ed

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoangdl-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-04e5d8fef121e9030