apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: file1
              valueFrom:
                configMapKeyRef:
                  name: myapp
                  key: file1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /hoangdl-data
              name: hoangdl-configmap
      volumes:
        - name: hoangdl-configmap
          configMap:
            name: myapp
            items:
              - key: file1
                path: file1
