apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    kubernetes.io/change-cause: first change
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-49-73.ap-southeast-1.compute.internal
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: hoangdl-emptydir
            mountPath: /home/hoangdl-emptydir
      - name: alpine
        image: alpine
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "tail -f /dev/null "
        volumeMounts:
          - name: hoangdl-emptydir
            mountPath: /data/hoangdl-emptydir
      volumes:
        - name: hoangdl-emptydir
          awsElasticBlockStore:
            volumeID: vol-072e4d15d5910ccc4