apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    kubernetes.io/change-cause: first change
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
      - name: nginx
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 5
          failureThreshold: 5
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "cat /usr/share/nginx/html/index.html" 
        image: nginx:1.14.2
        env:
          - name: abc
            value: "123"
          - name: abcde
            value: "@34"
        ports:
        - containerPort: 80
